<?php

/**
 * @return array
 */
function etype_zenfolio_menu()
{
  $items['admin/config/etype/etype_zenfolio/settings'] = [
    'title' => 'Zenfolio Settings',
    'description' => 'Enter user name and password for your Zenfolio account',
    'page callback' => 'drupal_get_form',
    'page arguments' => ['etype_zenfolio_admin_form'],
    'access arguments' => ['administer content'],
    'file' => 'etype_zenfolio.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  ];

  $items['zenfolio_test'] = [
    'title' => 'Zenfolio Test',
    'page callback' => '_etype_zenfolio_fetch',
    'access arguments' => array('administer content'),
    'type' => MENU_NORMAL_ITEM,
  ];

  return $items;
}

function _etype_zenfolio_fetch()
{
  $appname = 'eType Services/1.0 (www.etypeservices.com)';
  $username = variable_get('etype_zenfolio_username');
  $password = variable_get('etype_zenfolio_password');

  require_once 'vendor/autoload.php';

  try {
    $client = new phpZenfolio\Client($appname);
    $client->login($username, $password);
  } catch (Exception $e) {
    echo "{$e->getMessage()} (Error Code: {$e->getCode()})";
  }

  try {
    $pictures = $client->GetRecentPhotos(0, 10);
    array_walk($pictures, 'display_imgs');
    print_r($pictures);
  } catch (Exception $e) {
    echo "{$e->getMessage()} (Error Code: {$e->getCode()})";
  }

  function display_imgs(&$item, $key)
  {
    $item = $item->Title . '<a href="'.$item->PageUrl.'"><img src="'.phpZenfolio\Client::imageUrl($item, 1).'" title="'.$item->Title.'" alt="'.$item->Id.'" /></a>';
  }

}