<?php

/**
 * @return array
 */
function etype_zenfolio_menu()
{
  $items['admin/config/etype/etype_zenfolio/settings'] = [
    'title' => 'Zenfolio Settings',
    'description' => 'Enter user name and password for your Zenfolio account',
    'page callback' => 'drupal_get_form',
    'page arguments' => ['etype_zenfolio_admin_form'],
    'access arguments' => ['administer content'],
    'file' => 'etype_zenfolio.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  ];

  $items['zenfolio_test'] = [
    'title' => 'Zenfolio Test',
    'page callback' => '_etype_zenfolio_fetch',
    'access arguments' => array('administer content'),
    'type' => MENU_NORMAL_ITEM,
  ];

  return $items;
}

function etype_zenfolio_preprocess_node(&$variables)
{
  dpm($variables['content']);
  $node = $variables['node'];
  if (isset($node->field_zenfolio_photoset_id))
  {
    $zenfolio_photoset_id = $node->field_zenfolio_photoset_id['und'][0]['value'];
    $pictures = _etype_zenfolio_fetch($zenfolio_photoset_id);
    $markup = implode('', $pictures);
    $variables['content']['field_zenfolio_photoset_id']['#items'][0]['#markup'] = $markup;
  }
}

function _etype_zenfolio_fetch($photoset_id)
{

  $pictures = [];

  if (!empty($photoset_id))
  {
    $appname = 'eType Services/1.0 (www.etypeservices.com)';
    $username = variable_get('etype_zenfolio_username');
    $password = variable_get('etype_zenfolio_password');

    function display_imgs(&$item)
    {
      $item = $item->Title . '<a href="' . $item->PageUrl . '"><img src="' . phpZenfolio\Client::imageUrl($item, 1) . '" title="' . $item->Title . '" alt="' . $item->Id . '" /></a>';
    }

    require_once 'vendor/autoload.php';

    try {
      $client = new phpZenfolio\Client($appname);
      $client->login($username, $password);
    } catch (Exception $e) {
      echo "{$e->getMessage()} (Error Code: {$e->getCode()})";
    }

    try {
      // $pictures = $client->GetRecentPhotos(0, 10);
      $pictures = $client->LoadPhotoSetPhotos($photoset_id, 0, 10);
      // $pictures = $client->LoadGroupHierarchy($username);
      array_walk($pictures, 'display_imgs');
      // print_r($pictures);
    } catch (Exception $e) {
      echo "{$e->getMessage()} (Error Code: {$e->getCode()})";
    }
  }

  return ($pictures);

}