<?php

/**
 * @return array
 */
function etype_zenfolio_menu() {

  $items['admin/config/etype/etype_zenfolio/settings'] = [
    'title' => 'Zenfolio Settings',
    'description' => 'Enter user name and password for your Zenfolio account',
    'page callback' => 'drupal_get_form',
    'page arguments' => ['etype_zenfolio_admin_form'],
    'access arguments' => ['administer content'],
    'file' => 'etype_zenfolio.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  ];

  $items['zenfolio_test'] = [
    'title' => 'Zenfolio Test',
    'page callback' => '_etype_zenfolio_fetch',
    'access arguments' => array('administer content'),
    'type' => MENU_NORMAL_ITEM,
  ];

  return $items;
}

function _etype_zenfolio_fetch() {
  $appname = 'eType Services/1.0 (www.etypeservices.com)';
  $username = variable_get('etype_zenfolio_username');
  $password = variable_get('etype_zenfolio_password');

  require_once 'vendor/autoload.php';

  try {
    $client = new phpZenfolio\Client($appname);
    // Get list of recent galleries and collections
    $h = $client->LoadGroupHierarchy($username);
    // Now traverse the tree and locate the first public gallery and display it's first 96 photos
    array_walk($h->Elements, 'displayImgs', $client);
  } catch (Exception $e) {
    echo "{$e->getMessage()} (Error Code: {$e->getCode()})";
  }

  function displayImgs(\stdClass $element, $_, phpZenfolio\Client $client)
  {
    if ($element->{'$type'} == 'Group') {
      array_walk($element->Elements, 'displayImgs', $client);
    } else {
      if ($element->PhotoCount > 0) {
        $pictures = $client->LoadPhotoSetPhotos($element->Id, 0, 96);
        // Display the 60x60 cropped thumbnails and link to the photo page for each.
        foreach ($pictures as $picture) {
          echo '<a href="'.$picture->PageUrl.'"><img src="'.phpZenfolio\Client::imageUrl($picture, 1).'" title="'.$picture->Title.'" alt="'.$picture->Id.'" /></a>';
        }
      }
    }
  }

}